# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Egudenintg1hesscpp <- function(thetam, alphaX, gammaX, PsiX, ti, yi, Xi, Ai, tstari, beta_mu_vec, beta_A_vec, beta_mu_Ui_vec, beta_A_Ui_vec, knots, t_end, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights) {
    .Call(`_RetroJM_Egudenintg1hesscpp`, thetam, alphaX, gammaX, PsiX, ti, yi, Xi, Ai, tstari, beta_mu_vec, beta_A_vec, beta_mu_Ui_vec, beta_A_Ui_vec, knots, t_end, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights)
}

Egudenintg2hesscpp <- function(thetam, alphaX, gammaX, PsiX, ti, yi, Xi, Ai, tstari, longi_t, beta_mu_vec, beta_A_vec, beta_mu_Ui_vec, beta_A_Ui_vec, knots, t_end, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights) {
    .Call(`_RetroJM_Egudenintg2hesscpp`, thetam, alphaX, gammaX, PsiX, ti, yi, Xi, Ai, tstari, longi_t, beta_mu_vec, beta_A_vec, beta_mu_Ui_vec, beta_A_Ui_vec, knots, t_end, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights)
}

Egudenintg3hesscpp <- function(thetam, alphaX, gammaX, PsiX, ti, yi, Xi, Ai, tstari, longi_t, beta_mu_vec, beta_A_vec, beta_mu_Ui_vec, beta_A_Ui_vec, knots, t_end, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights) {
    .Call(`_RetroJM_Egudenintg3hesscpp`, thetam, alphaX, gammaX, PsiX, ti, yi, Xi, Ai, tstari, longi_t, beta_mu_vec, beta_A_vec, beta_mu_Ui_vec, beta_A_Ui_vec, knots, t_end, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights)
}

Egudenintg4hesscpp <- function(thetam, alphaX, gammaX, PsiX, ti, Xi, Ai, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights) {
    .Call(`_RetroJM_Egudenintg4hesscpp`, thetam, alphaX, gammaX, PsiX, ti, Xi, Ai, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights)
}

Egudenintg5hesscpp <- function(thetam, alphaX, gammaX, PsiX, ti, Xi, Ai, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights) {
    .Call(`_RetroJM_Egudenintg5hesscpp`, thetam, alphaX, gammaX, PsiX, ti, Xi, Ai, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights)
}

Egudenintg6hesscpp <- function(thetam, alphaX, gammaX, PsiX, ti, Xi, Ai, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights) {
    .Call(`_RetroJM_Egudenintg6hesscpp`, thetam, alphaX, gammaX, PsiX, ti, Xi, Ai, sty_end, surv_knots, drop_knots, surv_par_0, surv_par_1, drop_par_0, drop_par_1, tol, nodes, weights)
}

